development:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: my_database_development
  pool: 5